### PR TITLE
Fix checkbox and radio click handlers

### PR DESCRIPTION
**Pull request by oomathias**
Attach events handlers to the displayed component.

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks, but this looks like you've moved the input props to the element that's *not* the input. Am I missing something?

**Comment by oomathias** [comment]
Well yes, ignore this pull request as is.

But there is a problem, `onClick` is never called because it is attached to a hidden input.

I have the same issues with the `Radio` component. Were you able to control these inputs?

**Comment by oomathias** [comment]
You can try it here: https://esnextb.in/?gist=8cfe6cb9601083ca44d33e2ff6960c3f&exec=true
Remove line `62` to see the bug.

I had to embed some code since there are no `peerDependencies` declared in `axs` and `axs-ui`. I will make another PR for that.

**Comment by oomathias** [comment]
Updated with the correct fix.
`onClick` is now attached to the clickable component.

**Pull request closed without merging**
